### ISSUE TITLE
Enable Private vulnerability reporting

### ISSUE THREAD

**Issue by TristanCacqueray** [haskell/security-advisories#1]
It looks like GitHub offers such feature: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability

Though, it does not seem enabled on https://github.com/rustsec/advisory-db . I guess it is worth trying for this project.

**Comment by TristanCacqueray** [comment]
It is now enabled, the feature is available through the `Security` (top) -> `Advisories` (left) -> `New draft security advisory` (top green button), or directly through this url: https://github.com/haskell/security-advisories/security/advisories/new .

Though it seems like this feature is not suited for this project and it is more relevant for package repository. Once the haskell security-advisories database is registered at GitHub, advisories could refer to the Haskell ecosystem.

**Comment by frasertweedale** [comment]
Indeed, it seems that the intent is for reporting advisories against the actual GitHub repo/project, which is not quite what we are aiming to achieve.  But the form seems general enough - maybe we can still (ab)use it...

**Comment by TristanCacqueray** [comment]
Unfortunately that is not helpful for the project, so I've disabled it.
