### ISSUE TITLE
set up CI pipeline(s) for advisories

### ISSUE THREAD

**Issue by frasertweedale** [haskell/security-advisories#10]
Set up a CI pipeline for checking that advisories conform to our requirements.

For pull requests, it is probably sufficient to check only the advisories being added or modified, rather than the whole database.

For PRs that modify the tools, we should probably check the whole database, to find regressions or existing advisories that no longer meet our expectations (as those evolve).

**Comment by blackheaven** [comment]
For reference, I'm on the tool part of the CI: https://github.com/blackheaven/security-advisories/tree/tools/introduce-nix

**Comment by blackheaven** [comment]
Actually apply current (`main`) version of the tool.

Not an artifact to be kept up-to-date elsewhere.

**Comment by blackheaven** [comment]
We may also use `fkirc/skip-duplicate-actions` to improve build workflows.
