### ISSUE TITLE
CVSS type and support library

### ISSUE THREAD

**Issue by frasertweedale** [haskell/security-advisories#101]
## Summary

Implement a CVSS parsing and helper library.  Then update the Advisory library to use the CVSS type.

*Note:* the `cvss` field in some advisories may need adjustments to conform.

**Comment by akacase** [comment]
@frasertweedale -- should we also open issues regarding refining other types in our schema, e.g., `purl,` etc. I've been working on a simple purl parser [here](https://github.com/akacase/purl). I assume you're on the CVSS parser.

**Comment by frasertweedale** [comment]
@akacase I haven't started the CVSS work.  I plan to start it after the regression tests (#100) are implemented.  But if someone else wants to make a start, feel free.

Yes tickets for other type refinements (purl, etc) are a good idea.  Design / API topics can be discussed in the specific tickets.
