### ISSUE TITLE
Configure GitHub Pages

### ISSUE THREAD

**Issue by blackheaven** [haskell/security-advisories#133]
After merge #130, GitHub Pages aren't publish on https://haskell.github.io/security-advisories

Possible hints:

* GitHub Pages are disables at organization level:

> Organization owners can disable the publication of GitHub Pages sites from the organization's repositories.
>
> https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#about-github-pages

* It needs a haskell.github.io repository

> To publish an organization site, you must create a repository owned by an organization that's named `<organization>.github.io`
> 
> https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites

**Comment by frasertweedale** [comment]
This document shows how *Organization owners can manage the publication of GitHub Pages sites from repositories in the organization*: https://docs.github.com/en/organizations/managing-organization-settings/managing-the-publication-of-github-pages-sites-for-your-organization

**Comment by mihaimaruseac** [comment]
I think we actually have an issue with our setup, I triggered a new deploy and got the following run: https://github.com/haskell/security-advisories/actions/runs/7201137898

It seems it still thinks we are using Jekyll, so probably we still need to configure it to not do so.

**Comment by mihaimaruseac** [comment]
Got it working: https://haskell.github.io/security-advisories/

Now we just need to set a custom CNAME and maybe also test automation when a new advisory got published.
