### ISSUE TITLE
OSV JSON output of severity `type` and `score` are backwards

### ISSUE THREAD

**Issue by michaelkedar** [haskell/security-advisories#135]
## Summary
The severity fields in the outputted OSV JSON records seem to have been mixed up.
e.g. [HSEC-2023-0015](https://github.com/haskell/security-advisories/blob/8a9bd24dfcf1fb98d158ff9e64973bac8c162bc7/2023/HSEC-2023-0015.json#L1C162-L1C248) lists
```json
"severity":[{"score":"CVSS_V3","type":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:H/A:N"}]
``` 
instead of 
```json
"severity":[{"score":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:H/A:N","type":"CVSS_V3"}]
```

## Cause of the bug
I'm not familiar with Haskell, but it looks like it's just the `score` and `type` fields were mixed up here:
https://github.com/haskell/security-advisories/blob/d66c8e445c4bcae893575d1a92727cca6c2e6dce/code/hsec-tools/src/Security/OSV.hs#L173-L180

**Comment by frasertweedale** [comment]
Thank you for the detailed report.  We shall have a fix for this promptly!
