### ISSUE TITLE
`hsec-tools` nix package depends on `haskell-language-server` 

### ISSUE THREAD

**Issue by MangoIV** [haskell/security-advisories#144]
## Summary

`hsec-tools` nix package depends on `haskell-language-server` derivation.

## Steps to reproduce

`nix build github:haskell/security-advisories#hsec-tools` (will download hls) 

## Expected behavior

if we just want to run the `hsec-tools`, as `hls` doesn't get into the resulting `closure` (which it doesn't), we shouldn't have to downloads `hls` 

## Cause of the bug

https://github.com/haskell/security-advisories/blob/23c7af5495a09c812e90072191f71eba86a8785f/flake.nix#L42

I think this is the culprit.

**Comment by blackheaven** [comment]
Thanks for your feedback, it should be fixed in #146

**Comment by MangoIV** [comment]
Thank you!

**Comment by TristanCacqueray** [comment]
Thanks, this seems fixed according to:

```
$ nix run github:utdemir/nix-tree -- --derivation github:haskell/security-advisories#hsec-tools
/nix/store/fgi7f2vqmwadhwzqyr7bwy5nfyzbrc8n-hsec-tools-0.1.0.0.drv                                                                                             
NAR Size: 10.38 KiB | Closure Size: 4.75 MiB | Added Size: 4.75 MiB
```

Please re-open if the issue persists.
