### ISSUE TITLE
Schema: investigate CAPEC field

### ISSUE THREAD

**Issue by frasertweedale** [haskell/security-advisories#158]
Just out of curiosity. Is there a CAPEC field?

_Originally posted by @hasufell in https://github.com/haskell/security-advisories/pull/157#discussion_r1518465932_
            
CAPEC = *Common Attack Pattern Enumerations and Classifications*

See also: https://capec.mitre.org/

**Comment by blackheaven** [comment]
Is there something left to do?

**Comment by frasertweedale** [comment]
AFAICT this is done.  Closing it.
