### ISSUE TITLE
Cabal package publishing process

### ISSUE THREAD

**Issue by MangoIV** [haskell/security-advisories#177]
## Summary

it would be good to offer the tools provided in this repository as a package on hackage. 

For cabal-audit, Jude Taylor is asking me to whom they should transfer the maintainer rights of cabal-audit for the PR that adds that tool. 

Can any of the Haskell security working group please confirm whom to pass the maintainer rights to?

**Comment by frasertweedale** [comment]
Most definitely, we plan to do this soon.  I hope to tackle it during the next week or so.

**Comment by MangoIV** [comment]
@frasertweedale I don't wanna be pushy, but Joel really hurried up in making sure he can hand over the namespace so it would be kinda rude to keep him waiting for a long time, can you perhaps name an account that I can they can hand over the namespace `cabal-audit` to, for the time being? 

Thanks in advance!

**Comment by frasertweedale** [comment]
We have published our stuff on hackage.  @MangoIV as you are currently the owner/maintainer of cabal-audit, I think the Hackage namespace should be handed over to you.

**Comment by MangoIV** [comment]
Yeah, I habe to shoot Joel another mail :3 

thank you :)
