### ISSUE TITLE
No ISO 8601 parse for outputs of git into type `ZonedTime` 

### ISSUE THREAD

**Issue by MangoIV** [haskell/security-advisories#202]
## Summary

downstream may have issues parsing formats like this output by git `2024-05-30T16:15:18Z` into `ZonedTime` 

This makes oob timestamp parsing fail. the error is not printed, that's why the error is the most confusing

the reason for this behavior is that hsec-tools parses into `ZonedTime`. git may not output ZonedTime.

**Comment by frasertweedale** [comment]
Can you give an example commit or Git configuration that causes this issue, and describe how it was produced?

**Comment by MangoIV** [comment]
I cannot. The github runners just started failing. I printed the output of the git log command and it showed a non-offset time.

**Comment by MangoIV** [comment]
I also couldn’t influence this. I have to assume that git installations that are in UTC just output non-zoned time.
