### ISSUE TITLE
Are embargoed vulnerabilities accepted?

### ISSUE THREAD

**Issue by adamgundry** [haskell/security-advisories#204]
My understanding from speaking to @frasertweedale is that vulnerabilities subject to embargo are now accepted by the SRT, subject to resource constraints. However this contradicts the documents in this repo, which may need to be updated?

`CONTRIBUTING.md` curently says:
> Q: Does this project have a GPG key or other means of handling embargoed vulnerabilities?
> 
>  A: We do not presently handle embargoed vulnerabilities. Please ensure embargoes have been lifted and details have been disclosed to the public prior to filing them here.

`PROCESS.md` says:
> The HSRT does not presently handle embargoed vulnerabilities. Please ensure embargoes have been lifted and details have been disclosed to the public prior to filing a report.

**Comment by frasertweedale** [comment]
Thank you!  We will update the docs to reflect the current status.

**Comment by TristanCacqueray** [comment]
The PROCESS.md original document contains extensive information about how to handle the progressive disclosure and keep every party up to date. Now that we have a VINCE group, perhaps we could leverage this platform?

**Comment by mihaimaruseac** [comment]
+1 to using VINCE if possible.
