### ISSUE TITLE
Consistency of introduced versions and Hackage

### ISSUE THREAD

**Issue by tchoutri** [haskell/security-advisories#247]
In https://haskell.github.io/security-advisories/advisory/HSEC-2023-0009.html the "introduced version" that was declared is `0.1`. However it does not exist in Hackage.

The earliest version of `git-annex` in Hackage is [3.20110702](https://hackage.haskell.org/package/git-annex-3.20110702).

If this is not a typo and `0.1` is indeed the release in which the vulnerability was introduced, the advisory should be amended and follow https://haskell.github.io/security-advisories/advisory/HSEC-2023-0007.html where it is written:

```toml
# it was introduced earlier, but this is the earliest version on Hackage
introduced = "3.0.3.1"
```

It's not that I like being bureaucratic, it's just that flora.pm's data model expects consistency within Hackage when it comes to referencing versions, and `git-annex-0.1` simply does not exist in Hackage.

**Comment by blackheaven** [comment]
The thing is, it looks like it was a vulnerability introduced since the beginning.

I think we're reaching an interesting point: flora is now tightly coupled to `security-advisories` and tries to make it's integration to fit it's structure.

IMO it's generally not a good idea.

During our last SRT Meeting we proposed that flora use the osv format instead to reduce coupling, I'm not sure it'll fix the issue.

@mihaimaruseac how does OSV handles a vulnerability introduced since the beginning?

**Comment by tchoutri** [comment]
> I think we're reaching an interesting point: flora is now tightly coupled to security-advisories and tries to make it's integration to fit it's structure.

I guess I was mostly naïve about the consistency guarantees of the OSV format. Yes I could re-design the data model around the fact that the versions specified in the "hackage ecosystem" bit may not exist in Hackage, but since it's an immutable package index I didn't think it would happen.

If you can confirm that the version numbers will privilege VCS tags over hackage versions, or anything than would help the resolution of a version number, Ill be glad to adapt.

**Comment by mihaimaruseac** [comment]
I'll take a look at OSV for Haskell to see if you can make sure the versions are correct. Afaik, we should be able to specify that a vulnerability exists in all version before a given one, but need to check to be sure.

**Comment by tchoutri** [comment]
@mihaimaruseac does it make sense to refer to versions that do not exist on Hackage?

**Comment by mihaimaruseac** [comment]
I think using a placeholder for "since start of life of the package" would make sense. But it should be something that cannot be confused with a possible version (so `"0"` is ok, but `"0.1"` not)

**Comment by frasertweedale** [comment]
@tchoutri  wrote:
> does it make sense to refer to versions that do not exist on Hackage?

A project could have had a tarball releases, versions defined in the repo history, etc, without necessarily releasing those versions on Hackage.  I think it's tolerable to restrict the version field to actual released versions in the Hackage namespace (likewise for other namespaces).  But, if feasible, it would be good if Flora could handle unknown introduced/fixed versions in advisories and use comparison operators on the `Version` type to deduce whether some known package version is affected.

If it would help, we can add library functions to *hsec-core* to perform these sorts of checks.  It's already implemented in the `hsec-tools query` command so we only need to move some code around and expose a library function.
