### ISSUE TITLE
Export OSV database

### ISSUE THREAD

**Issue by TristanCacqueray** [haskell/security-advisories#25]
On advisory merge, we could generate the OSV version and push it to a branch, similar to what rustsec is doing with: https://github.com/rustsec/advisory-db/blob/main/.github/workflows/export-osv.yml

- [ ] Implement a converter to transform the Advisory data type into the desired JSON object
- [ ] Add a subcommand to the hsec-tools to convert one md file
- [ ] Implements a GitHub workflow action to publish to a osv branch

**Comment by frasertweedale** [comment]
This has been implemented in https://github.com/haskell/security-advisories/pull/78.
