### ISSUE TITLE
Generate a website with the list of advisories

### ISSUE THREAD

**Issue by TristanCacqueray** [haskell/security-advisories#31]
The goal is to have a website with the list of advisories.

- [ ] Design a site similar to https://rustsec.org/advisories/ using a library like blaze-html or lucid
- [x] Add a new website command to the hsec-tools to generate the list of advisory and the individual pages
- [x] Implements a GitHub workflow action to publish the website on page branch

**Comment by frasertweedale** [comment]
#85 added HTML index generation.  We just need to decide where to publish it now.

**Comment by gbaz** [comment]
big plus one on this. you can reach out to me or davean for getting a site setup on haskell.org resources if you'd like -- alternately you can use github pages and we can give a custom h.org domain?

**Comment by mihaimaruseac** [comment]
I think GitHub pages will be the easiest, we cna publish via CI

**Comment by blackheaven** [comment]
I can handle that part, I already did it three times.

**Comment by MangoIV** [comment]
is there any progress on this?

**Comment by MangoIV** [comment]
ah, the website exists; perhaps we can close this issue?
