### ISSUE TITLE
advisory metadata: allow multiple urls?  more fine-grained references?

### ISSUE THREAD

**Issue by frasertweedale** [haskell/security-advisories#37]
## Summary

The `url` TOML field is single-valued.  Should we support multiple URLs?  For example, the aeson vulnerability had a couple of detailed articles written about it, as well as an in-depth discussion in the GitHub issue.

Furthermore, the OSV schema recognises many types of references (e.g. advisory, article, fix, discussion, etc).  Perhaps we should reflect this in our advisory schema?

**Comment by mihaimaruseac** [comment]
+1, it would be nice to reflect multiple references and their relationships.

**Comment by frasertweedale** [comment]
I have an implement (based on #42).  Will submit a PR in the next day.
