### ISSUE TITLE
Register HSEC database and Hackage ecosystem in osv-schema

### ISSUE THREAD

**Issue by frasertweedale** [haskell/security-advisories#4]
osv-schema has a registry of advisory database identifiers (https://ossf.github.io/osv-schema/#id-modified-fields) and a registry of "package ecosystems" (https://ossf.github.io/osv-schema/#affectedpackage-field).  We should send a PR to register the HSEC advisory database, and Hackage (as well as, perhaps, GHC itself, e.g. see the definition for `Linux`).

**Comment by TristanCacqueray** [comment]
Once the system is in place, we should also create an issue for https://github.com/github/advisory-database#sources .

**Comment by frasertweedale** [comment]
I propose registering:

- `HSEC` database id
- `Hackage` ecosystem name
- `GHC` ecosystem name, for components of GHC itself (compiler, GHCi, RTS, etc)

**Comment by mihaimaruseac** [comment]
Working on this right now, will have a PR by end of week

**Comment by frasertweedale** [comment]
PR was merged: https://github.com/ossf/osv-schema/pull/157

But the updates have not been "released".  And we still need to give some examples.  So I guess we leave this open for now.

**Comment by frasertweedale** [comment]
Everything is done on the osv.dev side.  Probably we just need to add some examples to the osv-schema repo, and then we can close this.

**Comment by mihaimaruseac** [comment]
Yeah, I have left some TODOs there, I'll take care of them during this weekend.

**Comment by mihaimaruseac** [comment]
Closed accidentally due to the way I set-up the upstream/fork repos

**Comment by frasertweedale** [comment]
The osv-schema PR was merged.  This ticket is resolved.
