### ISSUE TITLE
lib/advisories: improve time handling (modified / published)

### ISSUE THREAD

**Issue by frasertweedale** [haskell/security-advisories#46]
OSV uses RFC3339 (ISO 8601) UTC timestamps for the `modified`, `published` and `withdrawn` fields.
We need to update our `Advisory` type to have distinct `modified` and `published fields`, with the required
precision.

I intend to update the parsing implementation to use `git log` to determine the appropriate values for `published`
and `modified`.  These values, respectively, will be the *commit* (not *author*) date of the first appearance of the file being parsed
(renames will be followed at Git's default similarity threshold), and the most recent modification to the file being parsed.
Because we are using the **rebase** merge strategy (in GitHub pull requests), the commit date will always be updated when merging to `main`.  So the dates represent when things were added to, or changed in, the `main` branch - which to me seems equivalent to the addition/modification being "published".
**Let me know what you think about this.**  Maybe there will be objections or alternative suggestions.

As for the `withdrawn` field, I will define it in the data type, but not parse anything yet.  We can't use the same heuristic to automatically infer a suitable value, so the SRT should discuss it.  *Defer until we someday need to withdraw an advisory* may be an appropriate decision.

**Comment by frasertweedale** [comment]
ping @mihaimaruseac ^ do you have any thoughts about the proposed approach?

**Comment by mihaimaruseac** [comment]
I think these should be ok. We can parse `withdrawn` in a similar way from the PR that removes it, though maybe let's cross this bridge when we get to it?
